package com.ztesoft.isap.server.webService.bnetV3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2019-05-15T16:11:21.698+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://www.BNET.cn/v3.0/", name = "CrmForBnetV3")
@XmlSeeAlso({ObjectFactory.class})
public interface CrmForBnetV3 {

    @WebResult(name = "SubApplyReturn", targetNamespace = "")
    @RequestWrapper(localName = "SubApply", targetNamespace = "http://www.BNET.cn/v3.0/", className = "com.ztesoft.isap.server.webService.bnetV3.SubApply")
    @WebMethod(operationName = "SubApply")
    @ResponseWrapper(localName = "SubApplyResponse", targetNamespace = "http://www.BNET.cn/v3.0/", className = "com.ztesoft.isap.server.webService.bnetV3.SubApplyResponse")
    public String subApply(
            @WebParam(name = "xmlString", targetNamespace = "")
                    String xmlString
    );

    @WebResult(name = "createResponseReturn", targetNamespace = "http://bnetV3.webservice.server")
    @RequestWrapper(localName = "createResponse", targetNamespace = "http://bnetV3.webservice.server", className = "com.ztesoft.isap.server.webService.bnetV3.CreateResponse")
    @WebMethod
    @ResponseWrapper(localName = "createResponseResponse", targetNamespace = "http://bnetV3.webservice.server", className = "com.ztesoft.isap.server.webService.bnetV3.CreateResponseResponse")
    public String createResponse(
            @WebParam(name = "isSuccess", targetNamespace = "http://bnetV3.webservice.server")
                    boolean isSuccess,
            @WebParam(name = "transactionId", targetNamespace = "http://bnetV3.webservice.server")
                    String transactionId
    );

    @WebResult(name = "DealResultReturn", targetNamespace = "")
    @RequestWrapper(localName = "DealResult", targetNamespace = "http://www.BNET.cn/v3.0/", className = "com.ztesoft.isap.server.webService.bnetV3.DealResult")
    @WebMethod(operationName = "DealResult")
    @ResponseWrapper(localName = "DealResultResponse", targetNamespace = "http://www.BNET.cn/v3.0/", className = "com.ztesoft.isap.server.webService.bnetV3.DealResultResponse")
    public String dealResult(
            @WebParam(name = "xmlString", targetNamespace = "")
                    String xmlString
    );
}
