
package com.ztesoft.isap.server.webService.bnetV3;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2019-05-15T16:11:21.622+08:00
 * Generated source version: 3.0.16
 * 
 */
public final class CrmForBnetV3_CrmForBnetV3ImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.BNET.cn/v3.0/", "CrmForBnetV3Impl");

    private CrmForBnetV3_CrmForBnetV3ImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CrmForBnetV3Impl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CrmForBnetV3Impl ss = new CrmForBnetV3Impl(wsdlURL, SERVICE_NAME);
        CrmForBnetV3 port = ss.getCrmForBnetV3ImplPort();  
        
        {
        System.out.println("Invoking subApply...");
        String _subApply_xmlString = "";
        String _subApply__return = port.subApply(_subApply_xmlString);
        System.out.println("subApply.result=" + _subApply__return);


        }
        {
        System.out.println("Invoking createResponse...");
        boolean _createResponse_isSuccess = false;
        String _createResponse_transactionId = "";
        String _createResponse__return = port.createResponse(_createResponse_isSuccess, _createResponse_transactionId);
        System.out.println("createResponse.result=" + _createResponse__return);


        }
        {
        System.out.println("Invoking dealResult...");
        String _dealResult_xmlString = "";
        String _dealResult__return = port.dealResult(_dealResult_xmlString);
        System.out.println("dealResult.result=" + _dealResult__return);


        }

        System.exit(0);
    }

}
