
package com.ztesoft.isap.server.webService.bnetV3;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2019-05-15T16:11:21.710+08:00
 * Generated source version: 3.0.16
 * 
 */
 
public class CrmForBnetV3_CrmForBnetV3ImplPort_Server{

    protected CrmForBnetV3_CrmForBnetV3ImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new CrmForBnetV3ImplPortImpl();
        String address = "http://136.127.56.23:7080/NpiServer/services/CrmForBnetV3ImplPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new CrmForBnetV3_CrmForBnetV3ImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
