package com.ztesoft.isap.server.webService.bnetV3;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2019-05-15T16:11:21.714+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebServiceClient(name = "CrmForBnetV3Impl", 
                  wsdlLocation = "http://136.127.56.23:7080/NpiServer/services/CrmForBnetV3ImplPort?wsdl",
                  targetNamespace = "http://www.BNET.cn/v3.0/") 
public class CrmForBnetV3Impl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.BNET.cn/v3.0/", "CrmForBnetV3Impl");
    public final static QName CrmForBnetV3ImplPort = new QName("http://www.BNET.cn/v3.0/", "CrmForBnetV3ImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://136.127.56.23:7080/NpiServer/services/CrmForBnetV3ImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CrmForBnetV3Impl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://136.127.56.23:7080/NpiServer/services/CrmForBnetV3ImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CrmForBnetV3Impl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CrmForBnetV3Impl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrmForBnetV3Impl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CrmForBnetV3Impl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CrmForBnetV3Impl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CrmForBnetV3Impl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CrmForBnetV3
     */
    @WebEndpoint(name = "CrmForBnetV3ImplPort")
    public CrmForBnetV3 getCrmForBnetV3ImplPort() {
        return super.getPort(CrmForBnetV3ImplPort, CrmForBnetV3.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrmForBnetV3
     */
    @WebEndpoint(name = "CrmForBnetV3ImplPort")
    public CrmForBnetV3 getCrmForBnetV3ImplPort(WebServiceFeature... features) {
        return super.getPort(CrmForBnetV3ImplPort, CrmForBnetV3.class, features);
    }

}
